name: FitNesse Result 
on: push
jobs:
  PublishFitNesseResult:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.19
      with:
        # The created test result check run has failure state if any test fails or test errors occur. Never fails when set to "nothing", fails only on errors when set to "errors". Default is "test failures".
        fail_on: test failures # optional, default is test failures
        # File patterns of test result files. Supports *, **, ?, and []. Use multiline string for multiple patterns.
        files: ./test-results/*.xml
